---

- name: "----: ADDING USER :-----"
  hosts: cluster
  become: yes
  vars_prompt:
   - name: username
     prompt: "Enter Username"
     private: no
   - name: user_groups
     prompt: "Enter teh groups name (separated by comma)"
     private: no
  roles:
    - { role: users }
