---

- name: Create group first
  group:
    name: "{{ username }}"
    state: present
  become: yes
  become_method: sudo

- name: ADD User
  user:
       name: "{{ username }}"
       shell: "{{ user_shell }}"
       group: "{{ username }}"
       groups: "{{ user_groups }}"
       createhome: True
       home: "{{ user_home }}"
       password: "{{ setting_password | string | password_hash('sha512', 'salty') }}"
       state: present
  become: yes
  become_method: sudo

- name: Change ownership of home directory
  file:
    path: "{{ user_home }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  become: yes
  become_method: sudo
